batch_size: 8
csv_path: /gpfs01/berens/user/jgervelmeyer/fovea_detection/Projects/fovea_od_localization/fovea_od_localization/data/ADAM+IDRID+REFUGE_df.csv
data_root: /gpfs01/berens/user/jgervelmeyer/fovea_detection/
device: cuda:0
epochs: 500
img_size: 350
lr: 0.0001
model_type: efficientnet-b3
seed: 123
testset_eval: true
