batch_size: 8
csv_path: /gpfs01/berens/user/jgervelmeyer/fundus_image_toolbox/fundus_fovea_od_localization/fundus_fovea_od_localization/data/ADAM+IDRID+REFUGE_df.csv
data_root: /path_to_parent_data_dir/
device: cuda:0
epochs: 1
img_size: 350
lr: 0.0001
model_type: efficientnet-b3
seed: 123
testset_eval: true
