[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "package/_version.py"

[options]
install_requires = []
setup_requires = ["setuptools_scm"]

[options.extras_require]
test = ["pytest", "pytest-cov"]